name: Build and Deploy Hugo site to main

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: source
          submodules: true # If you use Hugo themes as submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify --source personal-site

      - name: Add CNAME for custom domain
        run: echo "franzhenrymueller.de" > ./personal-site/public/CNAME

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./personal-site/public
          publish_branch: main
          force_orphan: true
